# AlertManager Configuration
# Handles alerts sent by Prometheus

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@infrastructure-learning.local'

# Route tree for organizing alerts
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

# Alert receivers - where to send notifications
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://localhost:5001/webhook'
    send_resolved: true

- name: 'critical-alerts'
  webhook_configs:
  - url: 'http://localhost:5001/critical'
    send_resolved: true
  # Add email, Slack, PagerDuty configs here

- name: 'warning-alerts'
  webhook_configs:
  - url: 'http://localhost:5001/warning'
    send_resolved: true

# Inhibit rules - suppress certain alerts when others are firing
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
