# Ansible inventory file in YAML format
# This defines the hosts and groups for your infrastructure

all:
  children:
    # Web servers group
    webservers:
      hosts:
        web1:
          ansible_host: 192.168.1.10
          ansible_user: ubuntu
          server_role: primary
        web2:
          ansible_host: 192.168.1.11
          ansible_user: ubuntu
          server_role: secondary
      vars:
        http_port: 80
        https_port: 443
        app_name: infrastructure-learning-app
    
    # Database servers group
    databases:
      hosts:
        db1:
          ansible_host: 192.168.1.20
          ansible_user: ubuntu
          db_role: master
        db2:
          ansible_host: 192.168.1.21
          ansible_user: ubuntu
          db_role: slave
      vars:
        db_port: 5432
        db_name: app_database
    
    # Load balancers group
    loadbalancers:
      hosts:
        lb1:
          ansible_host: 192.168.1.30
          ansible_user: ubuntu
      vars:
        lb_algorithm: round_robin
    
    # Monitoring servers
    monitoring:
      hosts:
        monitor1:
          ansible_host: 192.168.1.40
          ansible_user: ubuntu
      vars:
        grafana_port: 3000
        prometheus_port: 9090
    
    # Development environment
    development:
      hosts:
        dev1:
          ansible_host: localhost
          ansible_connection: local
      vars:
        environment: development
        debug_mode: true
    
    # Production environment
    production:
      children:
        webservers:
        databases:
        loadbalancers:
        monitoring:
      vars:
        environment: production
        debug_mode: false
        ssl_enabled: true

  # Global variables for all hosts
  vars:
    ansible_python_interpreter: /usr/bin/python3
    timezone: UTC
    ntp_servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
    dns_servers:
      - 8.8.8.8
      - 8.8.4.4
