# Prometheus configuration file
# This configuration sets up monitoring for the Flask application

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the Flask application metrics
  - job_name: 'flask-app'
    static_configs:
      - targets: ['web-app:4000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Monitor Redis if needed
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Monitor Nginx if needed (requires nginx-prometheus-exporter)
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx:9113']
  #   scrape_interval: 30s
