# Basic Pod Definition - Your First Kubernetes Resource
# A Pod is the smallest deployable unit in Kubernetes

apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  labels:
    app: web-app
    version: v1.0.0
    environment: learning
spec:
  containers:
  - name: web-app
    image: python:3.11-slim
    command: ["/bin/bash"]
    args:
      - "-c"
      - |
        pip install flask prometheus-client psutil && python -c "
        from flask import Flask, jsonify
        import time
        app = Flask(__name__)

        @app.route('/')
        def home():
            return jsonify({
                'message': 'Hello from Kubernetes Pod!',
                'pod_name': 'web-app-pod',
                'timestamp': time.time()
            })

        @app.route('/health')
        def health():
            return jsonify({'status': 'healthy', 'pod': 'web-app-pod'})

        if __name__ == '__main__':
            app.run(host='0.0.0.0', port=8080)
        "
    ports:
    - containerPort: 8080
      name: http
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
  restartPolicy: Always
