# Basic Service Definition - Network Access to Pods
# Services provide stable network endpoints for pods

apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  labels:
    app: web-app
spec:
  type: ClusterIP  # Internal cluster access only
  ports:
  - port: 80        # Service port
    targetPort: 8080 # Pod port
    protocol: TCP
    name: http
  selector:
    app: web-app    # Selects pods with this label

---
# NodePort Service - External access for testing
apiVersion: v1
kind: Service
metadata:
  name: web-app-nodeport
  labels:
    app: web-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080  # External port (30000-32767 range)
    protocol: TCP
    name: http
  selector:
    app: web-app
